<a href="https://colab.research.google.com/github/duke-sunshine/NYU-GameTheory-Summer2021/blob/main/Normal_Formal_Game_Milestone1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# install the tools you will use laterz
!pip install --upgrade setuptools
!pip install --upgrade pip
!pip install nashpy

# Abstract the Game

## Game illustration

In [ ]:
#@title Table1: Prisoner's Dilemma
# import module
from tabulate import tabulate
table = [['','','Prisoner B',''],
         ['','','confess','deny'],
         ['Prisoner A','confess','-3,-3','0,-6'],
         ['','deny','-6,0','-1,-1']]
print(tabulate(table,tablefmt='grid'))

+------------+---------+------------+-------+
|            |         | Prisoner B |       |
+------------+---------+------------+-------+
|            |         | confess    | deny  |
+------------+---------+------------+-------+
| Prisoner A | confess | -3,-3      | 0,-6  |
+------------+---------+------------+-------+
|            | deny    | -6,0       | -1,-1 |
+------------+---------+------------+-------+


In [ ]:
#@title Table1: Prisoner's Dilemma
import pandas as pd
import numpy as np
df2 = pd.DataFrame([['-3,-3','0,-6'],
                    ['-6,0','-1,-1']],
                  columns = [['Prisoner B','Prisoner B'],['confess','deny']],
                  index = [['Prisoner A','Prisoner A'],['confess','deny']])
df2

Prisoner B       
                      confess   deny
Prisoner A confess      -3,-3   0,-6
           deny          -6,0  -1,-1

## Define the Game Object

In [ ]:
import nashpy as nash
import numpy as np

# Creater the game with the payoff matrix

A = np.array([[-3,0],[-6,-1]]) # A is the row player (in this case, prisoner)
B = np.array([[-3,-6],[0,-1]]) # B is the column player

game1 = nash.Game(A,B)
game1

Bi matrix game with payoff matrices:

Row player:
[[-3  0]
 [-6 -1]]

Column player:
[[-3 -6]
 [ 0 -1]]

# Solve for Best Responses

In [ ]:
pip install quantecon

     |████████████████████████████████| 240 kB 9.9 MB/s 


In [ ]:
# import the package
import quantecon.game_theory as gt

/usr/local/lib/python3.7/dist-packages/numba/np/ufunc/parallel.py:363: NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 9107. The TBB threading layer is disabled.
  warnings.warn(problem)


In [ ]:
coordination_game_matrix = [[4, 0],
                            [3, 2]]  # square matrix
g_Coo = gt.NormalFormGame(coordination_game_matrix)

In [ ]:
print(g_Coo)


2-player NormalFormGame with payoff profile array:
[[[4, 4],  [0, 3]],
 [[3, 0],  [2, 2]]]


In [ ]:
g_Coo.players[0].payoff_array  # Player 0's payoff array

array([[4, 0],
       [3, 2]])

In [ ]:
g_Coo.players[1].payoff_array  # Player 1's payoff array

array([[4, 0],
       [3, 2]])

In [ ]:
g_Coo.players[0].best_response(1)

1

In [ ]:
g_Coo.players[0].best_response(0)

0

In [ ]:
g_Coo.players[0].best_response([0.5,0.5])

1

# Solve for Nash Equilibrium

## solve for the Nash Equilibrium

In [ ]:
#@title Table1: Prisoner's Dilemma
# import module
from tabulate import tabulate
table = [['','','Prisoner B',''],
         ['','','confess','deny'],
         ['Prisoner A','confess','-3,-3','0,-6'],
         ['','deny','-6,0','-1,-1']]
print(tabulate(table,tablefmt='grid'))

+------------+---------+------------+-------+
|            |         | Prisoner B |       |
+------------+---------+------------+-------+
|            |         | confess    | deny  |
+------------+---------+------------+-------+
| Prisoner A | confess | -3,-3      | 0,-6  |
+------------+---------+------------+-------+
|            | deny    | -6,0       | -1,-1 |
+------------+---------+------------+-------+


In [ ]:
# find the Nash equilibrium with Support Enumeration

equilibria = game1.support_enumeration()
for eq in equilibria:
    print(eq)

(array([1., 0.]), array([1., 0.]))


## calculate utility

In [ ]:
# Calculate Utilities

sigma_a = np.array([1,0])
sigma_b = np.array([1,0])
pd = nash.Game(A, B)
pd[sigma_a, sigma_b]

array([-3, -3])

## abstract the game

In [ ]:
#@title Table1: Prisoner's Dilemma
# import module
from tabulate import tabulate
table = [['','','Player B',''],
         ['','','Heads','Tails'],
         ['Player A','Heads','1,-1','-1,1'],
         ['','Tails','-1,1','1,-1']]
print(tabulate(table,tablefmt='grid'))

+----------+-------+----------+-------+
|          |       | Player B |       |
+----------+-------+----------+-------+
|          |       | Heads    | Tails |
+----------+-------+----------+-------+
| Player A | Heads | 1,-1     | -1,1  |
+----------+-------+----------+-------+
|          | Tails | -1,1     | 1,-1  |
+----------+-------+----------+-------+


In [ ]:
#@title Table1: Prisoner's Dilemma
import pandas as pd
import numpy as np
df2 = pd.DataFrame([['1,-1','-1,1'],
                    ['-1,1','1,-1']],
                  columns = [['Player B','Player B'],['Head','Tail']],
                  index = [['Player A','Player A'],['Head','Tail']])
df2

Player B      
                  Head  Tail
Player A Head     1,-1  -1,1
         Tail     -1,1  1,-1

## Define the Game Object

# Example 1: Matching Pennies

In [ ]:
import nashpy as nash
import numpy as np

# Creater the game with the payoff matrix

A = np.array([[1,-1],[-1,1]]) # A is the row player (in this case, prisoner)
B = np.array([[-1,1],[1,-1]]) # B is the column player

game2 = nash.Game(A,B)
game2

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

## calculating best response

In [ ]:
matching_pennies_bimatrix = [[(1, -1), (-1, 1)],
                             [(-1, 1), (1, -1)]]
g_MP = gt.NormalFormGame(matching_pennies_bimatrix)

In [ ]:
print(g_MP)

2-player NormalFormGame with payoff profile array:
[[[ 1, -1],  [-1,  1]],
 [[-1,  1],  [ 1, -1]]]


In [ ]:
print(g_MP.players[0])  # Player instance for player 0

Player in a 2-player normal form game with payoff array:
[[ 1, -1],
 [-1,  1]]


In [ ]:
print(g_MP.players[1])  # Player instance for player 1

Player in a 2-player normal form game with payoff array:
[[-1,  1],
 [ 1, -1]]


In [ ]:
g_MP.players[0].payoff_array  # Player 0's payoff array

array([[ 1, -1],
       [-1,  1]])

In [ ]:
g_MP.players[1].payoff_array  # Player 1's payoff array

array([[-1,  1],
       [ 1, -1]])

In [ ]:
g_MP[0, 0]  # payoff profile for action profile (0, 0)

array([ 1, -1])

In [ ]:
g_MP.players[0].best_response(1)

1

In [ ]:
# By default, returns the best response action with the smallest index
g_MP.players[0].best_response([0.5, 0.5])

0

In [ ]:
# With tie_breaking='random', returns randomly one of the best responses
g_MP.players[0].best_response([0.5, 0.5], tie_breaking='random')  # Try several times

1

In [ ]:

# With tie_breaking=False, returns an array of all the best responses
g_MP.players[0].best_response([0.5, 0.5], tie_breaking=False)

array([0, 1])

In [ ]:
g_MP.is_nash(([0.5, 0.5], [0.5, 0.5]))

True

In [ ]:
g_MP.is_nash((0, 0))

False

In [ ]:
g_MP.is_nash((0, [0.5, 0.5]))

False

## Solve for Nash Equilibrium

In [ ]:
# find the Nash equilibrium with Support Enumeration

equilibria = game2.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0.5, 0.5]), array([0.5, 0.5]))


In [ ]:
def print_pure_nash_brute(g):
    """
    Print all pure Nash equilibria of a normal form game found by brute force.
    
    Parameters
    ----------
    g : NormalFormGame
    
    """
    NEs = gt.pure_nash_brute(g)
    num_NEs = len(NEs)
    if num_NEs == 0:
        msg = 'no pure Nash equilibrium'
    elif num_NEs == 1:
        msg = '1 pure Nash equilibrium:\n{0}'.format(NEs)
    else:
        msg = '{0} pure Nash equilibria:\n{1}'.format(num_NEs, NEs)

    print('The game has ' + msg)

In [ ]:
print_pure_nash_brute(g_MP)

The game has no pure Nash equilibrium


## Caculating the Utility

In [ ]:
# Calculate Utilities

sigma_a = np.array([0.5,0.5])
sigma_b = np.array([0.5,0.5])
pd = nash.Game(A, B)
pd[sigma_a, sigma_b]

array([0., 0.])